'use strict';

(function () {
  var MANIFEST = '../output/layers.json';
  var PORTAL   = '../output/portal_items.json';

  function esc(s) {
    return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  function renderPortalSummary(items, portalHome) {
    if (!items || !items.length) return '';
    var total = items.length;
    var byType = {};
    items.forEach(function(i) {
      var t = i.type || 'Unknown';
      byType[t] = (byType[t] || 0) + 1;
    });
    var sorted = Object.keys(byType).sort(function(a, b) { return byType[b] - byType[a]; });
    var badges = sorted.map(function(t) {
      var encoded = encodeURIComponent(t);
      return '<a href="portal_item.html?type=' + encoded + '" class="pt-badge">' + esc(t) + ' <span>' + byType[t] + '</span></a>';
    }).join('');
    return '<div class="portal-summary">' +
      '<h2>Portal Items</h2>' +
      '<div class="ps-total">Total: <strong>' + total + '</strong> items &mdash; ' +
        '<a href="../output/portal_items.json">portal_items.json</a></div>' +
      '<div class="portal-types">' + badges + '</div>' +
      '</div>';
  }

  function renderLayers(layers) {
    if (!layers || !layers.length) return '<p id="loading">No layers found in output/layers.json.</p>';

    var html = '';
    var prevService = null;
    var prevFolder  = null;

    layers.forEach(function(layer) {
      var service = layer.service || '';
      var folder  = layer.folder  || null;

      if (service !== prevService) {
        if (prevService !== null) html += '</div>';
        html += '<div class="group"><div class="group-hdr">' + esc(service) + '</div>';
        prevService = service;
        prevFolder  = null;
      }

      if (folder !== prevFolder) {
        if (folder) {
          html += '<div class="sub-hdr">' + esc(folder) + '</div>';
        }
        prevFolder = folder;
      }

      var cls = folder ? 'item indent' : 'item';
      // Path in layers.json is relative to output/, e.g. "fgb/Service/Layer.fgb"
      // map.html needs a path relative to itself (in web/), so prefix ../output/
      var fgbParam = encodeURIComponent('../output/' + layer.path);
      html += '<div class="' + cls + '"><a href="map.html?fgb=' + fgbParam + '">' + esc(layer.name) + '</a></div>';
    });

    if (prevService !== null) html += '</div>';
    return html;
  }

  Promise.all([
    fetch(MANIFEST).then(function(r) { return r.json(); }).catch(function() { return null; }),
    fetch(PORTAL).then(function(r) { return r.json(); }).catch(function() { return null; })
  ]).then(function(results) {
    var manifest = results[0];
    var portalItems = results[1];

    var container = document.getElementById('container');
    var topbarSrc = document.getElementById('topbar-src');
    var footer    = document.getElementById('footer');

    if (!manifest) {
      container.innerHTML = '<p id="loading">Could not load <code>output/layers.json</code>. Run <code>download.sh</code> first.</p>';
      return;
    }

    // Update topbar with source URL
    if (manifest.baseUrl && topbarSrc) {
      topbarSrc.innerHTML = 'Source: <a href="' + esc(manifest.baseUrl) + '" target="_blank">' + esc(manifest.baseUrl) + '</a>';
      if (manifest.orgId) {
        topbarSrc.innerHTML += ' &mdash; Org ID: <a href="https://www.arcgis.com/home/search.html?q=orgid:' + esc(manifest.orgId) + '" target="_blank">' + esc(manifest.orgId) + '</a>';
      }
      topbarSrc.innerHTML += ' &mdash; Generated by download.sh';
    }

    var html = '';

    // Portal summary
    if (portalItems) {
      html += renderPortalSummary(portalItems, manifest.portalHome);
    }

    // Layer list
    html += renderLayers(manifest.layers);

    container.innerHTML = html;

    // Footer
    if (footer) {
      var count = manifest.layers ? manifest.layers.length : 0;
      footer.textContent = 'Updated: ' + (manifest.generatedAt || '') + ' \u2014 ' + count + ' layers';
    }
  });
})();
